# Generated by Django 3.2.8 on 2022-02-02 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0002_category_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectSite.service'),
        ),
    ]
