# Generated by Django 3.2.8 on 2022-02-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0003_contact_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='services',
        ),
    ]
