# Generated by Django 3.2.8 on 2022-02-03 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0004_remove_contact_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_ages',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_location',
        ),
    ]
