# Generated by Django 3.2.8 on 2022-02-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0007_auto_20220205_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
