# Generated by Django 3.2.8 on 2022-02-06 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0010_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='myvideos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectSite.videos'),
        ),
    ]
