# Generated by Django 3.2.8 on 2022-02-06 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0015_alter_videos_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='myvideos',
        ),
        migrations.AddField(
            model_name='videos',
            name='blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProjectSite.blog'),
        ),
    ]
