# Generated by Django 3.2.8 on 2022-02-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0017_auto_20220205_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='myvideos',
        ),
        migrations.AddField(
            model_name='blog',
            name='myvideos',
            field=models.ManyToManyField(blank=True, to='ProjectSite.Videos'),
        ),
    ]
