# Generated by Django 3.2.8 on 2022-02-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0020_auto_20220205_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
