# Generated by Django 3.2.8 on 2022-02-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0021_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
