# Generated by Django 3.2.8 on 2022-02-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0022_blog_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='orderingID',
            field=models.IntegerField(default=1),
        ),
    ]
