# Generated by Django 3.2.8 on 2022-02-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0023_category_orderingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='orderingID',
            field=models.IntegerField(default=1),
        ),
    ]
