# Generated by Django 3.2.8 on 2022-02-15 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0025_resident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='phone',
        ),
    ]
