# Generated by Django 3.2.8 on 2022-02-15 01:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0026_remove_resident_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
