# Generated by Django 3.2.8 on 2022-02-14 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0027_blog_test2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='test2',
        ),
    ]
