# Generated by Django 3.2.8 on 2022-02-14 23:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0028_remove_blog_test2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='test2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=True, null=True),
        ),
    ]
