# Generated by Django 3.2.8 on 2022-02-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0028_alter_resident_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='token',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
