# Generated by Django 3.2.8 on 2022-02-14 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0031_blog_test3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='test',
        ),
    ]
