# Generated by Django 3.2.8 on 2022-02-14 23:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0034_auto_20220214_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='test3',
        ),
        migrations.AddField(
            model_name='blog',
            name='test',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=True, null=True),
        ),
    ]
