# Generated by Django 3.2.8 on 2022-02-14 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0036_auto_20220214_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='test',
            new_name='post_content',
        ),
    ]
