# Generated by Django 3.2.8 on 2022-02-15 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0037_rename_test_blog_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='post',
        ),
    ]
