# Generated by Django 4.0.2 on 2022-02-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0039_event_event_popper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_popper',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
