# Generated by Django 4.0.2 on 2022-02-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0040_alter_event_event_popper'),
        ('ProjectSite', '0040_resident_phone'),
    ]

    operations = [
    ]
