# Generated by Django 4.0.2 on 2022-02-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0041_merge_20220226_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='image', max_length=128)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
