# Generated by Django 4.0.2 on 2022-03-03 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0043_event_interested_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Register', 'Register'), ('Registered', 'Registered')], default='Register', max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='interested',
            new_name='registered',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.AddField(
            model_name='register',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectSite.event'),
        ),
        migrations.AddField(
            model_name='register',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectSite.resident'),
        ),
    ]
