# Generated by Django 4.0.2 on 2022-03-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0044_register_rename_interested_event_registered_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
