# Generated by Django 4.0.2 on 2022-03-04 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectSite', '0045_delete_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registered',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
