# Generated by Django 4.0.2 on 2022-03-04 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0046_alter_event_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registered',
        ),
    ]
