# Generated by Django 4.0.2 on 2022-03-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0047_remove_event_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registered',
            field=models.ManyToManyField(blank=True, default=None, to='ProjectSite.Resident'),
        ),
    ]
