# Generated by Django 4.0.2 on 2022-03-28 03:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectSite', '0049_alter_event_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registered',
            field=models.ManyToManyField(blank=True, default=None, related_name='registeredUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
