# Generated by Django 4.0.2 on 2022-05-02 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectSite', '0050_alter_blog_main_image_alter_event_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Requested For Change', 'Requested For Change')], default='Pending', max_length=30),
        ),
        migrations.CreateModel(
            name='RequestService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_shortTerm', models.BooleanField(default=False, max_length=30)),
                ('education_longTerm', models.BooleanField(default=False, max_length=30)),
                ('employment_shortTerm', models.BooleanField(default=False, max_length=30)),
                ('employment_longTerm', models.BooleanField(default=False, max_length=30)),
                ('financial_shortTerm', models.BooleanField(default=False, max_length=30)),
                ('financial_longTerm', models.BooleanField(default=False, max_length=30)),
                ('healthcare_shortTerm', models.BooleanField(default=False, max_length=30)),
                ('healthcare_longTerm', models.BooleanField(default=False, max_length=30)),
                ('housing_shortTerm', models.BooleanField(default=False, max_length=30)),
                ('housing_longTerm', models.BooleanField(default=False, max_length=30)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
