# Generated by Django 4.0.2 on 2022-05-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0051_contact_contact_status_requestservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Requested For Change', 'Requested For Change')], default='Accepted', max_length=30),
        ),
    ]
